### PR TITLE
Update library to Contributors library standards

### PR DESCRIPTION
**Pull request by maxdeviant**
This PR updates `purescript-now` to adhere to the [Contributors library guidelines](https://github.com/purescript-contrib/governance/blob/main/library-guidelines.md).

This is part of the https://github.com/purescript-contrib/governance/issues/13 effort.

### CODE REVIEW

**Comment by maxdeviant** [comment]
Once this is merged we'll need issues for the following items:

- Adding a "quick start" guide
- Adding tests

**Review by thomashoneyman — COMMENTED** [review]
Thanks! Since CI isn’t yet running via GitHub Actions, would you mind sharing whether the build & test commands succeed (sometimes the new eslint config will fail, for example).

**Comment by maxdeviant** [comment]
`npm run build` is failing with the following error:

```
λ npm run build

> @ build /home/maxdeviant/projects/purescript-now
> eslint src && spago build --purs-args '--censor-lib --strict'

[info] Installation complete.
Invalid option `--censor-lib'

Usage: purs COMMAND
  The PureScript compiler and tools
[error] Failed to build.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `eslint src && spago build --purs-args '--censor-lib --strict'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     **/home/maxdeviant/.npm/_logs/2020-10-02T03_42_21_211Z-debug.log**
```

**Comment by thomashoneyman** [comment]
That error happens when `purescript-psa` isn't installed. If you don't have that on your system, then try running just:

```
npx eslint src && spago build
```

**Comment by maxdeviant** [comment]
Alright, looks like we're good!

```
λ npm run build

> @ build /home/maxdeviant/projects/purescript-now
> eslint src && spago build

[info] Installation complete.
[info] Build succeeded.

λ npm t

> @ test /home/maxdeviant/projects/purescript-now
> spago test --no-install

[info] Build succeeded.
🍝
You should add some tests.
[info] Tests succeeded.
```

**Review by thomashoneyman — APPROVED** [review]

**Comment by thomashoneyman** [comment]
The issue you linked in the Governance repository has issue templates you can use to create those issues. Thanks!

**Pull request merged**
